version = 1

[[analyzers]]
name = "docker"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = [
    "angularjs",
    "ember",
    "meteor",
    "vue",
    "react",
    "angular"
  ]
  environment = [
    "vitest",
    "mongo",
    "cypress",
    "mocha",
    "jasmine",
    "jquery",
    "jest",
    "nodejs",
    "browser"
  ]

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[transformers]]
name = "ruff"

[[transformers]]
name = "isort"

[[transformers]]
name = "yapf"

[[transformers]]
name = "autopep8"

[[transformers]]
name = "black"